	CREATE DATABASE SHOP1;
    USE SHOP1;
    CREATE TABLE SHOPE82(ID INT PRIMARY KEY auto_increment not null,ITEMS VARCHAR(70)NOT NULL,PRICE DECIMAL
    (10,2) NOT NULL,QUANTITY INT NOT NULL, LOCATION VARCHAR(50));
    INSERT INTO SHOPE82(ITEMS,PRICE,QUANTITY,LOCATION)VALUES('BELT',5000.00,10,'WUSE'),
    ('SHOES',20000.00,5,'DAWAKI'),('CAP',4000.00,5,'ZONE');
    SHOW TABLES;
    SHOW COLUMNS IN SHOPE82;
    SELECT*
    FROM SHOPE82;
    
    
    
    